version: '3.8'
services:
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: ORSDJANGO
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  web:
    build: ./django_project
    container_name: django_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_project:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=ORSDJANGO
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_PORT=3306

  frontend:
    build: ./python-project05
    container_name: angular_frontend
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  mysql_data: