# Generated by Django 5.2.14 on 2026-07-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'SOS_COLLEGE',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'SOS_COURSE',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobileNumber', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('college_ID', models.IntegerField(blank=True, default=0)),
                ('collegeName', models.CharField(blank=True, max_length=50)),
                ('subject_ID', models.IntegerField(blank=True, default=0)),
                ('subjectName', models.CharField(blank=True, max_length=50)),
                ('course_ID', models.IntegerField(blank=True, default=0)),
                ('courseName', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'SOS_FACULTY',
            },
        ),
        migrations.CreateModel(
            name='Marksheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNumber', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('physics', models.IntegerField()),
                ('chemistry', models.IntegerField()),
                ('maths', models.IntegerField()),
                ('year', models.IntegerField()),
                ('student_id', models.IntegerField()),
            ],
            options={
                'db_table': 'SOS_MARKSHEET',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'SOS_ROLE',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('mobileNumber', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('college_ID', models.IntegerField()),
                ('collegeName', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'SOS_STUDENT',
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('exam_time', models.CharField(max_length=50)),
                ('subject_id', models.IntegerField(default=0)),
                ('subject_name', models.CharField(blank=True, max_length=50)),
                ('course_id', models.IntegerField(default=0)),
                ('course_name', models.CharField(blank=True, max_length=50)),
                ('semester', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'SOS_TIMETABLE',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('login', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('role_id', models.IntegerField()),
                ('role_Name', models.CharField(blank=True, max_length=50)),
                ('mobileNumber', models.CharField(max_length=15)),
                ('gender', models.CharField(default='Male', max_length=10)),
                ('photo', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'db_table': 'SOS_USER',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('dob', models.DateField(blank=True, null=True)),
                ('course_ID', models.IntegerField(default=0)),
                ('courseName', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'SOS_SUBJECT',
                'unique_together': {('name', 'course_ID')},
            },
        ),
    ]
