# Generated by Django 5.2.14 on 2026-07-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('college_ID', models.IntegerField()),
                ('collegeName', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'SOS_DEPARTMENT',
            },
        ),
    ]
