# Generated by Django 5.2.14 on 2026-07-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(max_length=100)),
                ('department_ID', models.IntegerField(blank=True, default=0)),
                ('departmentName', models.CharField(blank=True, max_length=100)),
                ('appointmentDate', models.DateField(blank=True, null=True)),
                ('appointmentTime', models.CharField(max_length=50)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('mobileNumber', models.CharField(max_length=15)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
            options={
                'db_table': 'SOS_APPOINTMENT',
            },
        ),
    ]
