# Generated by Django 5.2.14 on 2026-07-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyName', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
            ],
            options={
                'db_table': 'sos_facultymodule',
            },
        ),
    ]
